sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifiations:
  email: false
node_js:
  - "7"
before_install:
  - "npm install -g npm@^2"
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release