sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifiations:
  email: false
node_js:
  - "10"
before_install:
  - "npm install -g npm@^2"
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release